baseURL = 'https://jamesandevie.com/'
languageCode = 'en-us'
title = "James & Evie' homepage"
theme = "jamesandevie"

[menus]
[[menus.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menus.main]]
name = "Contact"
pageRef = "/contact"
weight = 2

